export const config = {
  youtube: {
    size: 30,
    color: "white",
    id: 0,
    icon: "youtube",
    backgroundColor: "#cc0000",
  },
  download: {
    size: 18,
    color: "black",
    icon: "download",
    backgroundColor: "#0c131a",
    // width: "165px",
  },
  codetap: {
    size: 35,
    color: "white",
    id: 1,
    icon: "codetap",
  },
  facebook: {
    size: 35,
    color: "white",
    id: 2,
    icon: "facebook",
  },
  iconCross: {
    size: 30,
    color: "black",
    id: 8,
    icon: "cross",
  },
  linkedin: {
    size: 35,
    color: "white",
    id: 3,
    icon: "linkedin",
  },
  instagram: {
    size: 35,
    color: "white",
    id: 4,
    icon: "instagram",
  },
  stackoverflow: {
    size: 35,
    color: "white",
    id: 5,
    icon: "stackoverflow",
  },
  udemy: {
    size: 35,
    color: "white",
    id: 6,
    icon: "udemy",
  },
  skype: {
    size: 35,
    color: "white",
    id: 6,
    icon: "skype",
  },
  github: {
    size: 35,
    color: "white",
    id: 7,
    icon: "github",
  },
};
